import Head from 'next/head'
import { useState } from 'react';
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout'
import Image from 'next/image'
import porfilePic from "../../public/images/profile/developer-pic-1.png"
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import AnimatedText from '@/components/AnimatedText'
import { DownloadOutlined } from '@ant-design/icons'
import Link from 'next/link';
import HireMe from '@/components/HireMe';
import TransitionEffect from '@/components/TransitionEffect';




const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [size, setSize] = useState('large');
  return (
    <>
      <Head>
        <title>Sumon Hasan Portfolio Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TransitionEffect />
      <main className="bg-light">
        <Layout className='pt-0 md:pt-16 sm:pt-8 '>
          <div className='flex items-center justify-between w-full lg:flex-col'
            priority
            sizes="(max-width:768px) 100vw,
          (max-width:1200px) 50vw,
          50vw
          "
          >
            <div className='w-1/2 md:w-full lg:mb-5'>
              <Image src={porfilePic} alt='sumonhasan-profile-pic' className='h-auto md:inline-block md:w-full'>

              </Image>

            </div>
            <div className='flex flex-col items-center self-center w-1/2 lg:w-full lg:text-center'>
              <AnimatedText text="Dev.Sumon | Full-Stack Web Developer" className='!text-5xl !text-left xl:!text-5xl md:!text-justify  lg:!text-6xl md:text-2xl sm:!text-sm
              ' />
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs md:text-justify text-justify'>
              with experience in building scalable and responsive web applications. If you are looking for a skilled MERN stack web developer, feel free to check my resume and explore my latest projects, articles and reach at me.

               
              </p>

              <div className='flex items-center self-start mt-2 md:justify-items-start'>
                <Link href="/cv.pdf" target={"_blank"}
                  className="flex items-center bg-dark text-light dark:bg-light dark:text-dark p-2.5 px-6 rounded-lg text-lg font-semibold dark:hover:bg-dark dark:hover:text-light dark:hover:border-light hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark md:p-2 md:px-4 md:text-base"
                  download={true}
                >Resume<DownloadOutlined />

                </Link>

                <a href="mailto:wubsumon7577@gmail.com" target={"_blank"}
                  className='ml-4 text-lg font-medium underline capitalize md:mr-0 text-dark dark:text-light md:text-base'
                >Contact
                </a>
              </div>
            </div>

          </div>
        </Layout>
        <HireMe />
        <div className='absolute inline-block w-24 right-8 bottom-8'>
          <Image src={lightBulb} alt='' className='w-full h-auto lg:hidden'>

          </Image>
        </div>
      </main>
    </>
  )
}
